default: &default
  adapter: postgresql
  encoding: unicode
  username: bglmautam
  password: admin@bglmautam
  timeout: 5000
  host: localhost
  port: 5433
  pool: 5

development:
  <<: *default
  database: bglmautam_development

test:
  <<: *default
  database: bglmautam_test